version: '3.5'

services:

  postgis:
    container_name: postgis
    build: ./
    image: sign0/postgis-timescale-h3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgis}
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "15432:5432"
    expose:
      - "15432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgAdmin4}
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-8500}:80"
    networks:
      - postgres
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    depends_on:
      - postgis
    ports:
      - "8600:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel,mtanda-heatmap-epoch-panel, natel-usgs-datasource, snuids-radar-panel, natel-plotly-panel, briangann-datatable-panel
    volumes:
      - ./data/grafana:/var/lib/grafana     
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  grafana:
