version: '3.5'

services:

  postgis:
    container_name: postgis
    build: ./
    image: sahbi/postgis-timescale-h3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgis}
      PGDATA: /data/postgres
    volumes:
      - /srv/postgres:/data/postgres
      - ./initdb-extensions.sh:/docker-entrypoint-initdb.d/extensions.sh
    ports:
      - "15432:5432"
    expose:
      - "15432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgAdmin4}
    volumes:
       - /srv/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-8500}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  grafana: